package us.ilite.common.config;


import us.ilite.common.types.input.ELogitech310;

public class    DriveTeamInputMap {

    public static final ELogitech310
  
    DRIVER_TURN_AXIS = ELogitech310.RIGHT_X_AXIS,
    DRIVER_THROTTLE_AXIS = ELogitech310.LEFT_Y_AXIS,
    DRIVER_SUB_WARP_AXIS = ELogitech310.RIGHT_TRIGGER_AXIS,

    DRIVER_NUDGE_SEEK_LEFT = ELogitech310.L_BTN,
    DRIVER_NUDGE_SEEK_RIGHT = ELogitech310.R_BTN,

    DRIVER_TRACK_CARGO_BTN = ELogitech310.X_BTN,
    DRIVER_TRACK_TARGET_BTN = ELogitech310.A_BTN,
    DRIVER_TRACK_HATCH_BTN = ELogitech310.B_BTN,

    // Elevator
    OPERATOR_GROUND_POSITION_ELEVATOR = ELogitech310.A_BTN,
    OPERATOR_BOTTOM_POSITION_ELEVATOR = ELogitech310.X_BTN,
    OPERATOR_MIDDLE_POSITION_ELEVATOR = ELogitech310.Y_BTN,
    OPERATOR_TOP_POSITION_ELEVATOR = ELogitech310.B_BTN,

    OPERATOR_CONTROL_ELEVATOR = ELogitech310.RIGHT_Y_AXIS,

    //TODO Refactor to OPERATOR
    OPERATOR_CARGO_SELECT = ELogitech310.DPAD_RIGHT,
    OPERATOR_HATCH_SELECT = ELogitech310.DPAD_LEFT,
    OPERATOR_GROUND_SELECT = ELogitech310.DPAD_DOWN,
    OPERATOR_LOADING_STATION_SELECT = ELogitech310.DPAD_UP,
    OPERATOR_SCORE = ELogitech310.RIGHT_TRIGGER_AXIS,
    OPERATOR_ACQUIRE = ELogitech310.LEFT_TRIGGER_AXIS,
    OPERATOR_HANDOFF = ELogitech310.L_BTN;
}
